#!/bin/bash
# Make Desktop #1 all-floating

FLOATING_DESKTOP_ID=$(bspc query -D -d '^1')
bspc subscribe node | while read -a msg ; do
  desk_id=${msg[2]}
  wid=${msg[3]}
  echo ${msg[3]} ${msg[2]}
  [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done

