#!/bin/bash
# ~/.dmenurc
if [[ $HIDPI == "1" ]] ; then
  DMENU_FN="Liberation Mono:size=18"
else
  DMENU_FN="Liberation Mono:size=16.4"
fi
DMENU_NB="#111111"
DMENU_NF="#1ABB9B"
DMENU_SB="#1ABB9B"
DMENU_SF="#000000"
TERMINAL_CMD="$TERMINAL"
# notify-send $TERMINAL_CMD
PANEL_HEIGHT="25"
DMENU_OPTIONS="-nb $DMENU_NB -nf $DMENU_NF -sf $DMENU_SF -sb $DMENU_SB -i -l 15"
export DMENU_FN DMENU_NB DMENU_NF DMENU_SF DMENU_SB DMENU_OPTIONS PANEL_HEIGHT

