#!/bin/bash

if [ -z $1 ] ; then
  echo "Usage: fvim [-s] [-S VIMSESSION] dir/"
  exit
fi

# Parse options
TEMP=`getopt --long -o "sS:" "$@"`
eval set -- "$TEMP"
while true ; do
  # echo 11 $1 22 $2
  case "$1" in
    -s )
      sess=VIMSERV
      shift 1
    ;;
    -S )
      sess=$2
      shift 2
    ;;
    -- )
      location=$2
      shift 2
    ;;
    *)
      break
    ;;
  esac 
done;
# echo "session is $sess, location is $location"

if [ -n "$location" ] ; then 
  cd "$location"
fi
if [ -n "$sess" ] ; then
  EDITOR="vimz"
fi

file=$( du -a . | awk '{print $2}' | cut -c 3- | fzf --exact --height 55% )
echo $EDITOR "$file"
$EDITOR "$file"
[ -n "$sess" ] && raise.sh VIMSERV

