#!/bin/bash

FILE="/tmp/mpv-history"
# ignore '..' target 
if [ "$1" == '..' ]; then set -- "." "${2}" ; fi

# cd to $1
if [ -n "$1" ]
then
  if [ -e "$1" ]
  then
    cd "$1"
    echo we are in $PWD
    if ! [ -f "$FILE" ] ; then touch "$FILE" ; fi
    case `grep -xF "$PWD" "$FILE" >/dev/null; echo $?` in
      0)
        echo This album was listened to recently..
        ;;
      1)
        echo Updating history file..
        echo "$PWD" >> "$FILE"
        ;;
    esac
  else
    echo mpv-album says !No such directory!
    exit
  fi
fi

# set terminal title
if [ -n "$2" ]
then 
  echo -ne "\033]0;MPV @ $PWD @ $2\007"
else
  echo -ne "\033]0;MPV @ $PWD\007"
fi

if [[ $(ls | grep -ic '\.ape$\|\.flac$\|\.wv$') == $(ls | grep -ic '\.cue$') && $(ls | grep -ic '\.cue$') > 0 ]]
  then
  echo : play cue with mpv...
  mpv --pause --no-video *.cue
else
  echo : play audio files...
  mpv --pause --no-video *.{flac,mp3,ogg,ape,wv}
fi

