#!/bin/bash

# How many my vim-servers?
i=$(vim --serverlist | grep ^VIMSERV$ | wc -l)
# Launch great Vim
[ $i == 0 ] && echo $i &&
  case $TERMINAL in
    kitty*)
      # $TERMINAL --start-as maximized bash -c "source $HOME/.bashrc ; sleep .1 ; vim --servername vimserv" & ;;
      $TERMINAL bash -c "source $HOME/.bashrc ; sleep .1 ; vim --servername vimserv" & ;;
    *)
      xterm -maximized -e "source $HOME/.bashrc ; vim --servername vimserv" & ;;
  esac
[ $i == 0 ] && sleep 1.5

if ! [ -z "$1" ] ; then 
  # Escape spaces
  path=${1// /'\' }
  # prefix with current path
  path="$PWD/$path"
  if [[ $MODE == current ]] ; then
    # Edit in current Vim window
    vim --servername vimserv --remote-send "<c-w>:e $path<CR>"
  else
    if [[ $MODE == last ]] ; then
      # Edit in last Vim window
      vim --servername vimserv --remote-send "<c-w>p:e $path<CR>"
  else
    if [ $i == 0 ] ; then
      # Populate Vim buffer
      vim --servername vimserv --remote-send ":e $path<CR>" 
    else
      # Edit in new window in Vim
      vim --servername vimserv --remote-send "<c-w>:new $path<CR>" 
    fi
  fi
  fi
raise.sh VIMSERV &> /dev/null
else
  echo "Usage: [notab=1] vimz dir/file.txt"
fi

