#!/bin/bash
# vim: ts=2 sw=2 ft=sh
# Update and tidy my Arch Linux (or Debian Linux as well)

uptime -p
echo
# df -BGB
$LSBLK -o NAME,LABEL,MOUNTPOINT,SIZE,FSUSE% | grep "sd\|nvme" --color=none
# du -sh /var/log/journal/ $HOME
echo

# Call few commands with a single 'sudo' call
sudo bash -c "
(
  journalctl --vacuum-size=50M --quiet
  journalctl --disk-usage
  if  lsb_release -i | grep -q -ie 'mint\|debian\|buntu' ; then
    apt update
    apt upgrade
  elif  lsb_release -i | grep -q -ie "arch" ; then
    find /var/cache/pacman/pkg/ -mtime +7 -exec rm {} \; # Drop older package downloads
    echo
    [ -d /var/cache/pacman/pkg/ ] && du -sh /var/cache/pacman/pkg/
    pacman -Syu
  fi
  updatedb
)"

# Backup vim-session cause I am known to overwrite it by accident
[ -d $HOME/.vim ] && cp $HOME/.vim/session.vim $HOME/.vim/session.vimBAK

# Backup something else
[ -d "$tt" ] && bak.sh || echo "UNABLE TO MAKE TEXTS BACKUP!"

