#!/bin/bash
# vim: ts=4 sw=4 ft=sh
# Update and tidy my Arch Linux (or Debian Linux as well)

NVSD="$HOME/.nvim-session"

uptime -p ; echo

# Call few commands with a single 'sudo' call
sudo bash -c "
(
journalctl --vacuum-size=50M --quiet
# journalctl --disk-usage ; echo
echo -- Updating packages
if  lsb_release -i | grep -q -ie 'mint\|debian\|buntu' ; then
    apt update
    apt upgrade
elif  lsb_release -i | grep -q -ie 'arch\|manjaro' ; then
    pacman -Syy
    pacman -S --needed archlinux-keyring
    pacman -Syu
    find /var/cache/pacman/pkg/ -mtime +7 -exec rm {} \; # Drop older package downloads
    # du -sh /var/cache/pacman/pkg/
fi
updatedb
)"

# Backup vim-session cause I am known for overwriting it by accident
[ -f $HOME/.vim/session.vim ] && cp $HOME/.vim/session.vim $HOME/.vim/session.vimBAK
[ -d $NVSD ] &&
    tar -czf "$NVSD/sess.tar.gz" -C "$NVSD/" session

echo
du -sh $HOME
du -sh /var/log/journal/
[ -d /var/cache/pacman/pkg/ ] && du -sh /var/cache/pacman/pkg/ && echo
[ -d /var/cache/apt ] && { du -sh /var/cache/apt/ 2>/dev/null ; echo ; }

df -BGB --output=source,fstype,avail,pcent,target -x tmpfs -x devtmpfs
# $LSBLK -o NAME,LABEL,MOUNTPOINT,SIZE,FSUSE% | grep "sd\|nvme" --color=none ; echo

# Backup something else
echo -e "\n-- Starting bak.sh --"
DONTOVERWRITE=1 bak.sh

