#!/bin/bash
# Change notebook screen backlight power.

old=$(cat /sys/class/backlight/intel_backlight/brightness)
max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
if [ -z $1 ] ; then set -- "+0" ; fi
key=$(echo $1 | head -c 1)

case $key in
	u)
		new=$(expr $old + 1 + $old / 9)
		;;
	d)
		new=$(expr $old - 1 - $old / 9)
		;;
	+)
		new=$(expr $old + ${1:1})
		;;
	-)
		new=$(expr $old - ${1:1})
		;;
esac

if [ -z "$new" ] ; then
	new=$1;
fi

if [ $new -gt $max ] ; then 
	echo too much !
	new=$max
fi

if [ 0 -gt $new ] ; then
	echo too little !
	new=1
fi

echo Trying to set backlight to $new
echo $new > /sys/class/backlight/intel_backlight/brightness

echo -n 'New backlight value is '
cat /sys/class/backlight/intel_backlight/brightness
echo of $max possible

