#!/bin/bash

# Crucial locations #
# Note: $sh and $dotfiles should by now be sourced at $HOME/.bashrc
export git=$HOME/g
[[ ! -d $git ]] && [[ -d $sh ]] && [[ -d $(realpath "$sh/../../dotfiles") ]] &&
    export git=$(realpath "$sh/../..") && echo "$"git is a guess at $git
( [[ -z $dotfiles ]] || [[ ! -d $dotfiles ]] ) && [[ -d $git ]] && [[ -d $(realpath "$git/dotfiles") ]] &&
    export dotfiles=$(realpath "$git/dotfiles") &&
    echo NOTICE: "$"dotfiles were located at $dotfiles
[[ -d $dotfiles ]] || echo  WARNING! CANT FIND DOTFILES!
[ -d /ln/lo/cur ] && export loc=/ln/lo/cur || export loc=$HOME/.lo/cur
export vi=$dotfiles/vi

# Variables #
[ -z "${LANG}" ] &&   export LANG=en_US.UTF-8
[ -z "${LC_ALL}" ] && export LC_ALL=en_US.UTF-8
export HISTFILESIZE=
export HISTSIZE=9000
# [[ $COLORTERM == truecolor ]] && TERM=xterm-256color
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_DIRS=/usr/etc/xdg:/etc/xdg
export GUI_EDITOR=/usr/bin/xed
export EDITOR=vi
# export VIMINIT="source $vi/vimrc_main"
command -v  vim &>/dev/null && export EDITOR=vim
command -v nvim &>/dev/null && export EDITOR=nvim
export NVIMSERV=/tmp/neovimrpc
export VIMSERV=VIMSERV
# GPG_TTY=`tty`
export "GPG_TTY=$(tty)"
export PAGER=less
export BROWSER=firefox
export tt=$HOME/tt
export wd1=/ln/ho/proj
export bakhot=$HOME/bak
export bakusbdir=$(compgen -G /ln/mo/*AMV/bak)
export MANWIDTH=80
export LSBLK=lsblk
export OVMF=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd
export TERMINAL=xterm
command -v kitty &>/dev/null && export TERMINAL=kitty && export TERMINAL_BIGER="kitty -o initial_window_width=1330 -o initial_window_height=1060"
# [[ "$TERMINAL" == "kitty" ]] && [[ $HIDPI == "1" ]] && export TERMINAL="kitty -o font_size=14.2 -o initial_window_width=1140 -o initial_window_height=900"
[[ -z "$TERMINAL_BIGER" ]] && export TERMINAL_BIGER="$TERMINAL"

[[ $PATH == *"$sh"* ]] || export PATH=$PATH:"$sh"
[[ $PATH == *"$HOME/.local/bin"* ]] || export PATH=$PATH:$HOME/.local/bin
[[ -d $loc ]] && [[ $PATH == *"$loc"* ]] || export PATH=$PATH:$loc
( [[ -d $HOME/.local/share/gem/ruby/3.0.0/bin ]] && ! [[ $PATH == *"gem/ruby"* ]] ) && export PATH=$PATH:$HOME/.local/share/gem/ruby/3.0.0/bin
[[ $PATH == *"scoop"* ]] && export PATH=$(echo "$PATH" | sed -e 's|:\/mnt\/c\/Users\/[^/]*\/scoop\/apps\/perl.*current\/perl\/bin:|:|')
( [[ -d $HOME/.cargo/bin ]] && type -f rust &>/dev/null && ! [[ $PATH == *"/.cargo/bin"* ]] ) || export PATH=$PATH:"$HOME/.cargo/bin"


