#!/bin/bash

# Variables #
export HISTFILESIZE=
export HISTSIZE=9000
[[ $COLORTERM == truecolor ]] && TERM=xterm-256color
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_DIRS=/usr/etc/xdg:/etc/xdg
export GUI_EDITOR=/usr/bin/xed
export EDITOR=vi
command -v  vim &>/dev/null && export EDITOR=vim
command -v nvim &>/dev/null && export EDITOR=nvim
export NVIMSERV=/tmp/neovimrpc
export VIMSERV=VIMSERV
export PAGER=less
export BROWSER=firefox
export tt=$HOME/tt
#export jo=$HOME/gitjob
export git=$HOME/compy

#[[ -n $sh && -d $sh && -f $sh/bashrc ]] || 
#    { [ -d /ln/sh ] && export sh=/ln/sh || export sh=$HOME/.sh; }
#[[ -n $sh && -d $sh && -f $sh/bashrc ]] || 
#    { SELDIR=$(dirname $(realpath "$BASH_SOURCE")); echo rp is $SELDIR ; #[[ -d $SELDIR/vi && -f $SELDIR/all ]] && export sh="$SELDIR"; }




[[ -d $git ]] || export git=$(realpath "$sh/../..")
#echo sh is $sh
[ -d /ln/lo ] && export loc=/ln/lo/cur || export loc=$HOME/.lo/cur
export bakhot=$HOME/bak
export bakusbdir=$(compgen -G /ln/mo/*AMV/bak)
export MANWIDTH=80
export LSBLK=lsblk
export VIMINIT="source $sh/vi/vimrc_main"
export OVMF=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd
export TERMINAL=xterm
command -v kitty &>/dev/null && export TERMINAL=kitty && export TERMINAL_BIGER="kitty -o initial_window_width=1330 -o initial_window_height=880"
# [[ "$TERMINAL" == "kitty" ]] && [[ $HIDPI == "1" ]] && export TERMINAL="kitty -o font_size=14.2 -o initial_window_width=1140 -o initial_window_height=900"
[[ -z "$TERMINAL_BIGER" ]] && export TERMINAL_BIGER="$TERMINAL"
#
[[ $PATH == *"$HOME/.sh"* ]] || export PATH=$PATH:$HOME/.sh
[[ $PATH == *"$HOME/.local/bin"* ]] || export PATH=$PATH:$HOME/.local/bin
[[ $PATH == *"$loc"* ]] || export PATH=$PATH:$loc
