#!/bin/bash
# Main bashrc

export BASH_IS_PLASMIFIED=true

# [ -f $HOME/.bashrc_ORIG ] && source $HOME/.bashrc_ORIG
[ -f $HOME/.sh/bashrc ] && source $HOME/.sh/bashrc
[ -f $sh/bakrestosh.fn ] && source $sh/bakrestosh.fn
[ -f $loc/bashrc.local ] && source $loc/bashrc.local
