#!/bin/bash
# Turn current system into handy environment for me!

suc=false
var='v'
key=''

read_key() {
    echo Press   's' to enter shell , 'q' to exit , 'n' to go to next stage
    read -rsn 1 key
    [[ $key == 'f' ]] && echo key is F
    [[ $key == 'q' ]] && exit
    [[ $key == 'n' ]] && return
    [[ $key == 's' ]] && bash
}

if ($suc) ; then
    echo success
fi

cd

[[ -d Templates ]] && mkdir -p Trashed && mv Documents Music Pictures Public Templates Videos Trashed

if [[ -d $HOME/.dotfiles.git ]] ; then
    echo -e '\n'--Gonna update my git repo
    git -C "$HOME"/.dotfiles.git pull
else
    echo -e '\n'--Gonna clone my git repo
    git clone https://codeberg.org/plasmik/dotfiles "$HOME"/.dotfiles.git
fi

{
    echo -e '\n'--Gonna create /ln/ and short links there
    sudo mkdir -p /ln
    sudo chown $USER:$USER /ln
    cd /ln
    ln -sfnv $HOME ho
    ln -sfnv /ln/ho/.sh sh
    ln -sfnv /ln/ho/.lo lo
    ln -sfnv /mnt mo
    ln -sfnv /ln/ho/.config co
    ln -sfnv /ln/mo/blink bl
    ln -sfnv /ln/mo/fast fast
    ln -sfnv /ln/fast/hh hh
    ln -sfnv /ln/bl/torrents torrents
    # ln -sfnv /ln/mo/metal/MUSIC mus
    # ln -sfnv /ln/mo/blink/PRAGS pr
    ln -sfnv /ln/mo/metal/____ __
    # ln -sfn /ln/mo/blink/dwn dwn
    # ln -sfn /ln/ho/Downloads dwn
    # ln -sfn /ln/dwn /ln/ho/Downloads
}

{
    echo -e '\n'--Gonna link config files
    cd
    ! [[ -L .sh ]] && ln -sn .dotfiles.git/sh .sh
    ( [[ -f .bashrc ]] && ! [[ -L .bashrc ]] ) &&
        (
        echo --will move current .bashrc to exclusive trash file
        echo -e "\n\n----------$(date)-----.bashrc-------------\n\n" >> .bashrc_trash
        cat .bashrc >> .bashrc_trash
        rm .bashrc
        )
    ln -sf .sh/bashrc_main .bashrc
    # ln -sf .sh/Xresources .Xresources
    ln -sf .sh/vi/vimrc .vimrc
    mkdir -p /ln/co/nvim
    ln -srf .sh/vi/vimrc /ln/co/nvim/init.vim
    mkdir -p /ln/co/kitty
    ln -srf .sh/conf/kitty.conf /ln/co/kitty/
    mkdir -p /ln/co/feh
    ln -srf .sh/conf/feh.keys /ln/co/feh/keys
    mkdir -p /ln/co/zathura
    ln -srf .sh/conf/zathurarc /ln/co/zathura/
    mkdir -p /ln/co/vifm/colors
    cp .sh/conf/vifm-colors/*.vifm /ln/co/vifm/colors/
    ln -srf .sh/conf/vifmrc /ln/co/vifm/vifmrc
    mkdir -p /ln/co/mpv
    ln -srf .sh/conf/mpv/input.conf /ln/co/mpv/
    ln -srf .sh/conf/mpv/mpv.conf /ln/co/mpv/
    mkdir -p .local/share/applications/
    cp /ln/sh/conf/transmission*desktop .local/share/applications/
    #
    # xdg-mime default transmission-cli.desktop x-scheme-handler/magnet
    # xdg-mime default transmission-cli.desktop application/x-bittorrent
    xdg-mime default org.qbittorrent.qBittorrent.desktop x-scheme-handler/magnet
    xdg-mime default org.qbittorrent.qBittorrent.desktop application/x-bittorrent
    xdg-mime default FBReader.desktop application/x-mobipocket-ebook
    #
    sudo ln -sf /ln/sh/conf/99-libinput-custom.conf /etc/X11/xorg.conf.d/
}

# echo -e '\n'--Gonna pull some more config files
git -C ~/.config/kitty-themes/ pull ||
    git clone --depth 1 https://github.com/dexpota/kitty-themes.git ~/.config/kitty-themes
ln -sfrv .config/kitty-themes/themes/gruvbox_light.conf .config/kitty/current-theme.conf

