#!/bin/bash
# Make Desktop #1 all-floating, but ignore sticky or fullscreen windows

keep_floating () {
  FLOATING_DESKTOP_ID=$(bspc query -D -d "^$num")
  bspc subscribe node | while read -a msg ; do
    desk_id=${msg[2]}
    wid=${msg[3]}
    echo ${msg[2]} ':' ${msg[3]} ${msg[2]}
    # echo $(bspc query --tree -n ${wid} | grep sticky..true -c) 
    if 
      (
        [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] &&
        [[ ${wid} == $(bspc query -N -n "focused") ]] &&
          # check if bspc message is not garbage
        [ -z $(bspc query -N -n "${wid}.sticky") ] &&
          # ignore sticky windows
        [ -z $(bspc query -N -n "${wid}.fullscreen") ]
          # ignore fullscreen windows
      )
    then
      bspc node "$wid" -t floating
    fi
  done
}

for num in $FLOATING_DESK_NUM ; do
  keep_floating &
done

