#!/bin/bash

# xterm &
rc.sh &

bspc monitor -d 1 2 3 4 5 6 7 8
# bspc monitor HDMI-1 -d 1 2 3 
# bspc monitor HDMI-3 -d 4 5
# bspc monitor DVI-D-1 -d 4 5 6 7 8

bspc config border_width          3
bspc config window_gap            2
bspc config normal_border_color   "#333333"
bspc config active_border_color   "#505050"
bspc config focused_border_color  "#5E8448"

bspc config split_ratio          0.53
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a feh state=floating
bspc rule -a SpeedCrunch state=floating
bspc rule -a Fbreader state=floating
bspc rule -a Pidgin state=floating
bspc rule -a TelegramDesktop state=floating
bspc rule -a Nautilus state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a LearnOpenGL state=floating
bspc rule -a QjackCtl state=floating
bspc rule -a q4wine state=floating
bspc rule -a Wine state=floating
bspc rule -a VirtualBox state=floating
bspc rule -a Zathura state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# wmctrl -m | grep "Name:" | awk '{print $2}'
#   ( sleep .4 ; gsettings set org.gnome.mutter overlay-key '' )  # free Win key in Gnome 3

if [[ "$HOSTNAME" =~ ^debian10pc ]]; then
  bspc monitor HDMI-0 -d 4 5 6 7 8
  bspc monitor DVI-D-0 -d 1 2 3
  export FLOATING_DESK_NUM=5
else
  export FLOATING_DESK_NUM="1 2"
fi

( killall bspc bspc_rules & sleep .4 ; /./ln/sh/bspc_rules ) &

