#!/bin/bash

# xterm &

if ! [[ $1 == 'only' ]]; then
    # By default, run more DE stuff via other script
    xrc.sh &
fi

bspc monitor -d 1 2 3 4 5
# bspc monitor HDMI-1 -d 1 2 3
# bspc monitor HDMI-3 -d 4 5
# bspc monitor DVI-D-1 -d 4 5 6 7 8

bspc config border_width          3
bspc config window_gap            3
bspc config normal_border_color   "#333333"
bspc config active_border_color   "#505050"
# bspc config focused_border_color  "#5E8448"
bspc config focused_border_color  "#53944A"
bspc config presel_feedback_color "#C57E87"
bspc config presel_feedback       false

bspc config split_ratio          0.57
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config honor_size_hints     false
# bspc config automatic_schem    spiral
bspc config automatic_scheme     alternate
# bspc config directional_focus_tightness low

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a org.remmina.Remmina desktop='^3'
bspc rule -a feh state=floating
bspc rule -a feh:*:DUMMY state=tiled
bspc rule -a PyCalibr state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a SpeedCrunch state=floating
bspc rule -a Gpick state=floating
bspc rule -a FBReader state=floating
bspc rule -a Pidgin state=floating
bspc rule -a TelegramDesktop state=floating
bspc rule -a Nautilus state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a LearnOpenGL state=floating
bspc rule -a QjackCtl state=floating
bspc rule -a q4wine state=floating
bspc rule -a noita.exe border=off
bspc rule -a Wine state=floating
bspc rule -a VirtualBox state=floating
bspc rule -a Zathura state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a koi_to_sis state=floating
bspc rule -a koi_to_sis:koi_to_sis: state=fullscreen
# bspc rule -a kitty:kitty:kitty state=fullscreen

# wmctrl -m | grep "Name:" | awk '{print $2}'
#   ( sleep .4 ; gsettings set org.gnome.mutter overlay-key '' )  # free Win key in Gnome 3
# [[ -z ${FLOATING_DESKTOPS+x} ]] || export FLOATING_DESKTOPS

if [[ "$HOSTNAME" =~ ^bigstation ]]; then
    [[ -z ${FLOATING_DESKTOPS+x} ]] && FLOATING_DESKTOPS=5
    bspc monitor HDMI-0 -d 4 5 6 7 8
    bspc monitor DVI-D-0 -d 1 2 3
    bspc monitor HDMI-1 -d 1 2 3
    bspc monitor HDMI-2 -d 4 5 6 7 8
elif [[ "$HOSTNAME" =~ ^debianPC ]]; then
    [[ -z ${FLOATING_DESKTOPS+x} ]] && FLOATING_DESKTOPS='1 5'
    bspc monitor DP-1 -d 1 2 3 4 5
    bspc monitor DP-2 -d 6 7 8 9
elif [[ "$HOSTNAME" == "machine" ]]; then
    [[ -z ${FLOATING_DESKTOPS+x} ]] && FLOATING_DESKTOPS='3 4'
else
    [[ -z ${FLOATING_DESKTOPS+x} ]] && FLOATING_DESKTOPS=4
fi

# (
# killall bspc bspc_rules & sleep .4
killall bspc bspc_rules
export FLOATING_DESKTOPS
$sh/bspc_rules
# ) &

notify-send 'Bspwmrc complete'

