#!/bin/bash
# Call feh so it behaves like greatest IrfanView

# FEH_PARAMS="--auto-rotate --edit -B #333 -Fxnq."
# FEH_PARAMS="-B #333 -Fxnq."
FEH_PARAMS="--auto-rotate --edit -B #333 -rFxnq."
FEH_PARAMS_NOR="--auto-rotate --edit -B #333 -Fxnq."

# echo pwd is `pwd`
# echo 1 is "$1"

if  [ -d "$1" ]; then
  [ "$1" == "." ] && [[ $HOME == $PWD ]] && FEH_PARAMS=$FEH_PARAMS_NOR
  feh $FEH_PARAMS "$1" &>/dev/null &
elif [ -f "$1" ]; then
  dir=$(dirname \./"$1")
  file="${1#$dir}"
  echo dir file : $dir $file
  # if [ "$dir" == "./." ]; then # $1 was messed by vifm
  #   notify-send "biiiiiiiiiiiingo"
  #   feh $FEH_PARAMS --start-at "$file" . &>/dev/null &
  # else
    cd "$dir"
    [[ $PWD == $HOME ]] && FEH_PARAMS=$FEH_PARAMS_NOR
    feh $FEH_PARAMS --start-at ./"$file" . &>/dev/null &
  # fi
fi

