#!/bin/bash
# call nice feh

FEH_PARAMS="--auto-rotate -B #333 -Fxnq."
echo pwd : `pwd`
echo feha arg : \'"$1"\'

if [ "$1" = "." ]
then
  feh $FEH_PARAMS . &>/dev/null &
elif [ -d "$1" ]
then
  feh $FEH_PARAMS "$1" &>/dev/null &
elif [ -f "$1" ]
then
  dir="$(dirname \./"$1")"
  file="${1#$dir}"
  echo dir file : $dir $file 
  # check if $1 was messed by vifm
  if [ "$dir" == "./." ]
  then
    feh $FEH_PARAMS --start-at "$file" . &>/dev/null &
  else
    cd "$dir"
    feh $FEH_PARAMS --start-at ./"$file" . &>/dev/null &
  fi
fi

