#!/bin/bash
# Turn current system into suitable environment for me!

suc=false
var='v'
key=''

read_key() {
    echo Press   's' to enter shell , 'q' to exit , 'n' to go to next stage
    read -rsn 1 key
    [[ $key == 'f' ]] && echo key is F
    [[ $key == 'q' ]] && exit
    [[ $key == 'n' ]] && return
    [[ $key == 's' ]] && bash
}

if ($suc) ; then
    echo success
fi

{
    echo -e '\n'--Gonna clone my git repo
    cd
    # cd && rm -rf .dotfiles.git && mkdir .dotfiles.git && cd .dotfiles.git
    git clone https://github.com/010penetrator/dotfiles .dotfiles.git
}

{
    echo -e '\n'--Gonna create /ln/ and short links there
    sudo mkdir /ln
    sudo chown $USER:$USER /ln
    cd /ln
    ln -sn $HOME ho
    ln -sn /ln/ho/.sh sh
    ln -sn /ln/ho/.lo lo
    ln -sn /mnt mo
    ln -sn /ln/ho/.config co
    # ln -sn /ln/mo/blink/dwn dwn
    # ln -sn /ln/ho/Downloads dwn
    # ln -sn /ln/dwn /ln/ho/Downloads
    ln -sn /ln/mo/blink bl
    ln -sn /ln/mo/blink/hh hh
    ln -sn /ln/bl/torrents torrents
    ln -sn /ln/mo/metal/MUSIC mus
    ln -sn /ln/mo/blink/PRAGS pr
    ln -sn /ln/mo/metal/____ __
}

{
    echo -e '\n'--Gonna link config files
    cd
    ln -sn .dotfiles.git/sh .sh
    ( [[ -f .bashrc ]] && ! [[ -L .bashrc ]] ) &&
        (
        echo --will move current .bashrc to exclusive trash file
        echo -e "\n\n----------$(date)-----.bashrc-------------\n\n" >> .bashrc_trash
        cat .bashrc >> .bashrc_trash
        )
    ln -s .sh/bashrc_main .bashrc
    # ln -sf .sh/Xresources .Xresources
    ln -s .sh/vi/vimrc .vimrc
    mkdir -p /ln/co/nvim
    ln -srfv .sh/vi/vimrc .config/nvim/init.vim
    mkdir -p /ln/co/kitty
    ln -srfv .sh/conf/kitty.conf .config/kitty/
    ln -srfv .sh/conf/feh.keys .config/feh/keys
    sudo ln -sfv /ln/sh/99-libinput-custom.conf /etc/X11/xorg.conf.d/
    mkdir -p .config/vifm/
    ln -sv .sh/conf/vifmrc .config/vifm/vifmrc
    mkdir -p .local/share/applications/
    cp /ln/sh/transmission*desktop .local/share/applications/
    # xdg-mime default transmission-cli.desktop x-scheme-handler/magnet
    # xdg-mime default transmission-cli.desktop application/x-bittorrent 
}

{
    echo -e '\n'--Gonna pull some more config files
    git clone --depth 1 https://github.com/dexpota/kitty-themes.git ~/.config/kitty-themes
    ln -sfrv .config/kitty-themes/themes/gruvbox_light.conf .config/kitty/current-theme.conf
}

