#!/bin/bash
# Play youtube URL in clipboard via mpv

if [[ $(xclip -selection clipboard -o | grep youtu) ]] ; then
  adr=$(xclip -selection clipboard -o)
elif [[ $(xclip -o | grep youtu) ]] ; then
  adr=$(xclip -o)
fi

mpv $adr -ytdl-format='bestvideo[height<=720]+bestaudio'

