#!/bin/bash
# Store in a file the current phase of day
# Call 'nowis day' or 'nowis nox'
# Call 'nowis' or 'nowis what' to ask

if [[ -z $* || $1 == 'what' ]]; then
    if [[ -f /tmp/nowis && $( cat /tmp/nowis | wc -w ) -gt 0 ]]; then
        reply=$(cat /tmp/nowis | head -1 | cut -d ' ' -f1)
    else
        reply='dunno'
    fi
    notify-send -t 800 $reply
    echo $reply
    exit
fi

rm /tmp/now_is_* &> /dev/null
touch /tmp/now_is_"$1"
echo "$1" > /tmp/nowis

if [[ $1 == 'nox' ]]; then
    nitrogen --set-zoom-fill  $git/wlp/twisted_by_zy0rg_d5sdf8q.png
    sed -i 's/=Pop$/=Pop-dark/' /ln/co/gtk-3.0/settings.ini
    # Dim and warm screen
    type redshift &>/dev/null && { ga=.93; redshift -o -m randr -O 5100 -g $ga:$ga:$ga ; }
elif [[ $1 == 'day' ]]; then
    nitrogen --set-zoom-fill  $git/wlp/blues_by_tatasz_d8snwfz.png
    sed -i 's/=Pop-dark$/=Pop/' /ln/co/gtk-3.0/settings.ini
    # Undo nighttime screen dimming
    type redshift &>/dev/null && redshift -x -m randr
fi

{
    cd /ln/co/kitty/
    DT="day-theme.conf"
    NT="nox-theme.conf"
    CT="current-theme.conf"
    # Backup current theme if it is different from day theme and night theme
    if [[ -f $CT ]] && ! cmp -s $CT $DT && ! cmp -s $CT $NT ; then
        cp -f $CT prev_theme.conf
    fi
    if [[ $1 == 'nox' ]]; then
        [[ -f $NT ]] && rm $CT && cp -f $NT $CT
    elif [[ $1 == 'day' ]]; then
        [[ -f $DT ]] && rm $CT && cp -f $DT $CT
    fi
}

