#!/bin/bash
# Store in a file the current time of day
# Call 'nowis day' or 'nowis nox'

rm /tmp/now_is_* &> /dev/null

touch /tmp/now_is_"$1"

{
    cd /ln/co/kitty/
    DT="day_theme.conf"
    NT="nox_theme.conf"
    CT="current-theme.conf"
    # Backup current theme if it is different from day theme and night theme
    if [[ -f $CT ]] && ! cmp -s $CT $DT && ! cmp -s $CT $NT ; then
        cp -f $CT prev_theme.conf
    fi
    if [[ $1 == 'night' || $1 == 'nox' ]] ; then
        [[ -f $NT ]] && cp -f $NT $CT
    elif [[ -f $DT ]] ; then
        [[ -f $DT ]] && cp -f $DT $CT
    fi
}

if [[ $1 == 'nox' ]] ; then
    sed -i 's/=Pop$/=Pop-dark/' /ln/co/gtk-3.0/settings.ini
    # Dim and warm screen
    ga=.9; redshift -O 4900 -g $ga:$ga:$ga & disown
elif [[ $1 == 'day' ]] ; then
    sed -i 's/=Pop-dark$/=Pop/' /ln/co/gtk-3.0/settings.ini
    # Undo nighttime screen dimming
    redshift -x
fi

