#!/usr/bin/env python3
# Open files in existing nVim via RPC feature

import os, sys

# Env setup is lower merit, cli setup is higher
serv = (os.getenv('NVIMSERV'))
if (os.getenv('MODE')):
    mode = (os.getenv('MODE'))
else: # introduce default option here
    mode = 'newtabinsert'
file = ''

def get_cli_input():
    import getopt
    global serv,mode,file
    try:
        argv = sys.argv[1:]
        opts, args = getopt.getopt(argv, "s:m:")
    except getopt.GetoptError:
        print('usage: nvim_rpc.py -s /tmp/NVRPCSERVER -m newtab /etc/file')
        # sys.exit(2)
    for o, a in opts:
        print('stage c1', o, a)
        if o == '-s':
            serv = a
        if o == '-m':
            mode = a
    if args:
        file = args[0]
    else:
        print('Target file not provided!')
        file = '.'
    if not os.path.exists((serv)):
        print('RPC address', serv, 'is not present!\nWill launch nVim listening to that address.')
        start_neovim()
        os.system('sleep .4')
    # else:
    #     os.system("ror.sh ' - NVIM$' ''")

def start_neovim():
    global serv,mode
    mode = ''
    print('serv is ', serv)
    os.system('NVIMSERV=' + serv + ' nvimnew')

# Okay, we will actually do stuff now

get_cli_input()
print('argv..', sys.argv, len(sys.argv) )
print('file is', file)

from pynvim import attach
nvim = attach('socket', path=serv)

file = os.path.join( os.getcwd(), file )
print('final address', file)
print('mode', mode)

# Select/create window for editing the file
if mode == 'last':
    nvim.command('wincmd p')
    nvim.command('e ' + file)
elif mode == 'newtab':
    nvim.command('tabe ' + file)
elif mode == 'newtabinsert':
    nvim.command('-tabe ' + file)
elif mode == 'vert':
    nvim.command('vsplit ' + file)
elif mode == 'split':
    nvim.command('split ' + file)
else:
    nvim.command('e ' + file)

