#!/bin/bash
# Kill a process and start it afterwards

if [ -z "$TIMES" ] ; then
    TIMES=50
fi

if [ -z "$1" ] ; then
    echo Please provide a program name to restart it!
    exit
else
    PROC="$1"
fi

if [ -z "$2" ] ; then
    echo You also may provide command to launch via the second arg..
    COM="$1"
else
    COM="$2"
fi
co=0
while ( [[ $(pgrep -x "$PROC" | wc -l) > 0 ]] && [[ $co -le $TIMES ]] ) ; do
    sleep .1
    pkill -x "$PROC"
    ((co=co+1))
done

if [[ $(pgrep -x "$PROC" | wc -l) == 0 ]] ; then
    echo Will start $COM now..
    sleep .1
    # exec $COM &
    bash -c "$COM &"
else
    echo No success killing $PROC!
fi

