#!/bin/bash
# Download a video from youtube

if [ -z $1 ] ; then
  echo "Usage: tube [720] https://youtube......video"
  exit
fi

cd /ln/hh/yt 2>/dev/null || cd /ln/dwn
if ! [ -z $2 ]
then a="bestvideo[height<=$1]+bestaudio"
  echo format is $a
else if ! [ -z $1 ]
then youtube-dl $1
  a="bestvideo[height<=720]+bestaudio"
fi
fi

youtube-dl -f "$a" $2

echo .
echo 'output is:' 
ls -lh "$PWD"/*"$(echo "$@" | cut -d = -f2)".*
cd - &>/dev/null

