#!/bin/bash
# Download a video from youtube

if [ -z $1 ] ; then
  echo "Usage: tube [720] https://youtube......video"
  exit
fi

UTIL=youtube-dl
UTIL=yt-dlp

cd /ln/hh/yt 2>/dev/null || cd /ln/dwn
if ! [ -z $2 ]
then
  url=$2
  $UTIL --no-mtime -f "bestvideo[height<=$1]+bestaudio" $url
elif ! [ -z $1 ]
then
  url=$1
  $UTIL --no-mtime -f "bestvideo[height<=1080]+bestaudio" $url
fi

outnamewild="$PWD"/*"$(echo "$url" | cut -d = -f2)"*
outname=$(ls $outnamewild)

echo .
echo 'output is:'
echo \"$outname\"
# ls -lh $outnamewild

echo .
mediainfo "$outname" | grep 'pixels\|bits\|Video\|Audio\|Format  \|rate'

cd - &>/dev/null

