#!/bin/bash
# Spawn new Vim in a terminal, with RPC server

RPC_OPTION=''
if [ -z "$VIMSERV" ]
then
  echo "Servername not provided!"
else
  RPC_OPTION="--servername $VIMSERV"
fi

# Do we even have client-server compiled into Vim?
if vim --version | grep "-clientserver" -q; then
  RPC_OPTION=""
else
  # How many my vim-servers?
  i=$(vim --serverlist | grep ^VIMSERV$ | wc -l)
  [ $i != 0 ] && VIMSERV="''" && \
    echo Caution. Vim server already running. i will not make one more && sleep 1
fi

pgrep -c Xorg &>/dev/null && HASG=true
HASG=false

VIM="vim $RPC_OPTION"
[[ $VIMINSTASESS == true ]] && VIM="$VIM -c SLoad!"

if [[ $HASG == true ]]; then
  case $TERMINAL in
    kitty*)
      $TERMINAL --start-as maximized bash -c "source $HOME/.bashrc ; sleep .1 ; $VIM"
      ;;
    *)
      xterm -maximized -e "source $HOME/.bashrc ; sleep .1 ; $VIM"
      ;;
  esac
else
  vim $RPC_OPTION
fi

