#!/bin/bash
# Remote call vim or nvim

source $HOME/.bashrc

echo editor is $EDITOR
# echo args are $*

if [ -z "$1" ] ; then
  echo "Usage: [VIMSERV=name] [MODE=cur,last,newtab,newtabinsert,vert,split] vir file.c"
  # exit 1
fi

if [[ $EDITOR == nvim ]]; then
    echo ed is nvim
    nvimrpc.py $*
elif [[ $EDITOR == vim ]]; then
    echo ed is vim
    vimrpc $*
fi

