#!/bin/bash
# RPC-call vim or nvim

source $HOME/.bashrc

# echo EDITOR is $EDITOR
# echo args are $*

if [ -z "$1" ] ; then
  echo "Usage: [VIMSERV=name] [MODE=cur,last,newtab,newtabinsert,vert,split] virpc file.c"
  # exit 1
fi

if [[ $EDITOR == nvim ]]; then
    echo EDITOR is nvim
    nvimrpc.py $*
elif [[ $EDITOR == vim ]]; then
    echo EDITOR is vim
    vimrpc $*
fi

