# Usage: startx ~/.xinitrc awesome -- :0
session=${1:-startlxqt}
# xrdb -merge $sh/Xresources
setxkbmap -layout 'us,ru' -option 'grp:alt_shift_toggle,grp_led:scroll' &

case $session in
    awesome           ) exec /usr/bin/awesome;;
    bspwm             ) exec bspwm -c $sh/bspwmrc;;
#    catwm             ) exec catwm;;
#    cinnamon          ) exec cinnamon-session;;
#    dwm               ) exec dwm;;
#    enlightenment     ) exec enlightenment_start;;
#    ede               ) exec startede;;
#    fluxbox           ) exec startfluxbox;;
    gnome             ) exec gnome-session;;
#    gnome-classic     ) exec gnome-session --session=gnome-classic;;
    i3|i3wm           ) exec i3;;
#    pekwm             ) exec pekwm;;
#    icewm             ) exec icewm-session;;
#    jwm               ) exec jwm;;
#    kde               ) exec startkde;;
#    mate              ) exec mate-session;;
#    monster|monsterwm ) exec monsterwm;;
#    notion            ) exec notion;;
    openbox           ) exec /usr/bin/openbox-session;;
    lxqt              ) exec /usr/bin/startlxqt;;
#    unity             ) exec unity;;
#    xfce|xfce4        ) exec startxfce4;;
#    xmonad            ) exec xmonad;;
     chromium         ) exec /usr/bin/chromium;;
# Не известная сессия, попробуйте запустить в качестве команды
    *) exec $1;;
esac
