" vim: ts=4 sw=4 ft=vim
" This file should be sourced as $MYVIMRC

command! -nargs=1 SSource if filereadable(expand('<args>')) | source <args> | endif

SSource $sh/vi/init.vim
SSource $sh/vi/vimrc_themes

SSource $sh/vi/init.lua
SSource $sh/vi/nvim-lsp.lua


SSource $lo/vimrc.local
SSource $HOME/.vimrc_msys

